# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19i3pOLrfR29scv68Q2QdfhhA6pdTN4Wx
"""

import numpy as np
import matplotlib.pyplot as plt
n = 17
x = np.linspace(50, 825, 32)
y = np.array([62, 74.7, 79.7, 82, 93.4, 94, 105, 113.82, 139, 135, 138, 130, 148, 160, 161, 170, 175.25, 182.05, 195, 198, 199, 209.37, 220, 227, 229.9, 239, 243.5, 240.33, 243, 269, 270.8, 285])
K = [y[0]]
c = 0
for c in range(0,len(y),2):
  K.append(y[c+1])
  T = [x[0]]
  c = 0
  for c in range (0,len(x),2):
    T.append(x[c+1])
del K[0:1]     #skip value 1
del T[0:1]   
print(K)
print(T)