# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LbcTX5iSfIVS9_bbEiwWA89QcPEPSBEy
"""

import numpy as np
import matplotlib.pyplot as plt
n = 12
T = np.linspace(50, 825, 32)
K = np.array([62, 74.7, 79.7, 82, 93.4, 94, 105, 113.82, 139, 135, 138, 130, 148, 160, 161, 170, 175.25, 182.05, 195, 198, 199, 209.37, 220, 227, 229.9, 239, 243.5, 240.33, 243, 269, 270.8, 285])
y = [K[0]]
c = 1
for c in range(0,len(K),2):
  y.append(K[c+1])
  x = [T[0]]
  c = 1
  for c in range (0,len(T),2):
    x.append(T[c+1])
print(y)
print(x)
sumT = 0
sumT_sq = 0 
sumK = 0 
sum_T_K = 0


for i in range (n):
    sumT = sumT + x[i]
    sumT_sq= sumT_sq + x[i]**2
    sumK = sumK + y[i]
    sum_T_K = sum_T_K + x[i]*y[i]
    
    #Finding the coefficients
    m = (n*sum_T_K - sumT*sumK)/ (n*sumT_sq- sumT**2)
    b = (sumK*sumT_sq - sumT*sum_T_K)/  (n*sumT_sq- sumT**2)
   
print('\nCoefficients are:')
print('m:', m)
print('b:', b)

x_1 = np.linspace(50, 825, 17)
y_1 = b + m*x_1



print('K = {:.4f} + ({:.4f})x'.format(b,m))
plt.plot(x,y, 'ob', x_1, y_1)
plt.xlabel('x')
plt.ylabel('y')
plt.legend(['given points','b + m*x'])
plt.title('Linear fit')
plt.grid('on')
plt.show()
def y_1(x):
 return b + m*x